UPDATE BLC_SKU SET LONG_DESCRIPTION='The super-sized, slipcased Adamantium Collection format is back, and it''s the X-Men''s turn in the spotlight! It''s the best and brightest moments from the mighty mutants'' long and storied history, like you''ve never seen them before - and packed with dozens of extras! Thrill to the X-Men''s debut, seminal battles against Magneto and the Sentinels, the classic Days of Future Past and God Loves, Man Kills stories, Magneto''s return, Cyclops and Jean Grey''s wedding, Cassandra Nova''s deadly attack on mutantkind, the discovery of a cure for mutation, the X-Men''s exodus to San Francisco, and the original teen team''s shocking arrival in the present day'  WHERE SKU_ID=10000001;
UPDATE BLC_SKU SET LONG_DESCRIPTION='It''s the strangest, smashing-est Hulk yet! The green goliath discovers that to remain himself - and prevent the diabolical Dr. Banner from re-emerging - he must STAY ANGRY! The Hulk picks fights against drug cartels, sea monsters, Russian super-soldiers and a lost city of Sasquatches - oh, and the Punisher, Kraven the Hunter, Wolverine and the Thing! But when Banner''s devious master plan is revealed, and Dr. Doom returns, it''s a monumental day of reckoning for both Hulk and Banner! Hulk wants a piece of Doom, Banner plays an endgame of his own, and it all leads to an explosive conclusion'  WHERE SKU_ID=10000002;
UPDATE BLC_SKU SET LONG_DESCRIPTION='A NEW YORK TIMES #1 BESTSELLER
The Justice League is the greatest force for good the world has ever seen. But not everyone sees them that way.
Their never-ending battle against evil results in casualties beyond its super-powered, costumed combatants. The League’s attempts to safeguard innocent lives cannot save everybody. Unbeknownst to Earth’s greatest champions, their greatest triumph may contain the seeds of their greatest defeat.
For heroes are not the only people who face tragedy and are reborn as something greater than they were before. Villains can take this journey, too.
And once they start out on this dark path, the road could lead straight to the destruction of the Justice League…. 
'  WHERE SKU_ID=10000003;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Yet to be written'  WHERE SKU_ID=10000004;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Florence: Harvard symbologist Robert Langdon awakes in a hospital bed with no recollection of where he is or how he got there. Nor can he explain the origin of the macabre object that is found hidden in his belongings.

A threat to his life will propel him and a young doctor, Sienna Brooks, into a breakneck chase across the city. Only Langdon''s knowledge of the hidden passageways and ancient secrets that lie behind its historic facade can save them from the clutches of their unknown pursuers.

With only a few lines from Dante''s Inferno to guide them, they must decipher a sequence of codes buried deep within some of the Renaissance''s most celebrated artworks to find the answers to a puzzle which may, or may not, help them save the world from a terrifying threat.'  WHERE SKU_ID=10000005;
UPDATE BLC_SKU SET LONG_DESCRIPTION='The Lost Symbol by Dan Brown is a mind-numbing, racy thriller set within a 12-hour period that sends the protagonist, Robert Langdon, on a wild race to find the keys that would unlock the secrets of freemasonry.'  WHERE SKU_ID=10000006;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Harvard professor Robert Langdon receives an urgent late-night phone call while on business in Paris: the elderly curator of the Louvre has been brutally murdered inside the museum.Alongside the body, police have found a series of baffling codes.As Langdon and a gifted French cryptologist, Sophie Neveu, begin to sort through the bizarre riddles, they are stunned to find a trail that leads to the works of Leonardo Da Vinci - and suggests the answer to a mystery that stretches deep into the vault of history.'  WHERE SKU_ID=10000007;
UPDATE BLC_SKU SET LONG_DESCRIPTION='he Immortals of Meluha is the first book of the Shiva Trilogy. The book is about the discovery of the Neelkanth and the arrival of Shiva and his tribe to the city of Meluha. The Suryavanshi rulers and their empire is facing trouble and Shiva is the only one who can save them.'  WHERE SKU_ID=10000008;
UPDATE BLC_SKU SET LONG_DESCRIPTION='The Secret of the Nagas begins with Shiva trying to save Sati from a Naga attack. His quest for the Naga warrior who killed Brahaspati and assaulted Sati leads Shiva and Sati to the land of the Brangas. In The Secret of Nagas, Shiva the prophesied savior of the Meluhan Empire finds himself in a turbulent situation trying to avenge the murder of his friend and saving his clan and the people of Meluha from the evil serpent people.His journey takes him across the lengths and breadths of the ancient India, searching for the truth and answers to all his intriguing questions. He travels to Kashi to find every bit of detail about the Nagas. He comes to learn about the reason behind the alliance between the Brangas and the Nagas. Both Shiva and Sati eventually discover startling secrets that have profound effects on both their lives and relationship. With a war brewing in the backdrop, will Shiva be able to accept the truth and live up to the expectations attached to him?'  WHERE SKU_ID=10000009;
UPDATE BLC_SKU SET LONG_DESCRIPTION='India’s own super hero is finally here. Shiva has risen yet again to destroy the evildoers. The last of the Shiva Trilogy, this book promises to keep the readers gripped while the great warrior discovers who his true enemies are and gives it his all to destroy them.'  WHERE SKU_ID=10000010;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Master of The Game revolves around the MacGregor/Blackwell family and Kate Blackwell in particular. Kate is one of the richest and most powerful women in the world. The story starts with her ninetieth birthday celebration which is attended by other powerful people and dignitaries. She is hugely enigmatic with innumerable mysteries surrounding her. Her father earned riches beyond his imagination a long time back as a diamond prospector. Her mother, on the other hand, was born to a sly Afrikaner merchant. Her birthday celebrations see participation and toasts from prominent people like a judge of the Supreme Court. The White House also sends a telegram. The old lady herself sees the specters of long gone friends and enemies surround her on her birthday.'  WHERE SKU_ID=10000011;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Nothing Lasts Forever is a riveting suspense thriller penned by the master storyteller. It is an international bestseller that brings to you the story of three women doctors are unexpectedly hurled into a spotlight in the frenzied world of a big hospital.'  WHERE SKU_ID=10000012;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Master of The Game revolves around the MacGregor/Blackwell family and Kate Blackwell in particular. Kate is one of the richest and most powerful women in the world. The story starts with her ninetieth birthday celebration which is attended by other powerf'  WHERE SKU_ID=10000013;
UPDATE BLC_SKU SET LONG_DESCRIPTION='A touch of a button could mean the end of the world as we know it....Mary Ashley, beautiful, talented, intelligent, bas been chosen as the American Ambassador to Romania. Thrust from her comforting, homely life in Kansas, she finds herself lost amongst the political turmoil in a foreign country where she is seen as the enemy and no – one is to be trusted.
Then someone starts to threaten Mary and her children. Who can want her to leave so desperately and why? And can Mary decide who she can trust when her life is on the line?
'  WHERE SKU_ID=10000014;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' A Song of Ice And Fire takes place across two continents, Westeros and Essos. In these regions, seasons last for years. It has been summer for many years, but winter is approaching, and the turn of the season also triggers many momentous events. There are three distinct storylines, although they are ultimately interconnected.

Many centuries ago, the Seven Kingdoms that ruled Westeros were united under the powerful Targaryen Dynasty, who had the service of fire-breathing dragons at their disposal. This dynasty came to an end when the dragons apparently became extinct.

There was a power struggle over the Iron Throne, once held by the Targaryens and the last Targaryen ruler was killed in a rebellion led by Robert Baratheon.

Now, after Robert’s death, his young son, the cruel and self-absorbed Prince Joffrey, occupies the throne, supported by his mother and her powerful family, the Lannisters. The northern fiefdoms in Westeros are held by the powerful Eddard Stark, who swears allegiance to Robert Baratheon.

In the far northern border of Westeros, there is a huge, centuries old Wall of Ice. This is the only barrier that protects Westeros from the unearthly beings called the Others. And, there are the Wildlings, humans who live beyond the wall. This Wall is protected by the sentinels of the Night’s Watch.

In Essos, the story follows the fortunes of young Daenerys Targaryen, the only known heir to the House of Targaryen. Her character grows through the series, from a innocent young girl sold into marriage, to a strong young woman who wants to reclaim the Iron Throne.
Complicating the situation are rival claimants to the Iron Throne who want Joffrey out of the way. The most prominent among these is Stannis Baratheon, brother to Robert Baratheon.

A Song of Ice And Fire (Set of 6 Books) slowly builds up the strife and tension, and is an epic tale of murder, treachery, intrigue, and ambition under the ever present shadow of the enigmatic Others. This series has been adapted for television by HBO, as Game Of Thrones. The six books in this set are A Game of Thrones, A Feast For Crows, A Clash Of Kings, A Dance With Dragons, A Storm Of Swords 1: Steel and Snow and A Storm Of Swords 2: Blood and Gold.'  WHERE SKU_ID=10000015;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' The series, A Song Of Ice And Fire, narrates an epic fantasy story that is set in Westeros and Essos, two separate continents that share an ancient history and are linked by a common dynasty. The first two novels trace the events in Westeros after the death of the last king of the Targaryen Dynasty. The third book is set in the continent of Essos, where the last known descendant of the Targaryen line, Daenerys Targaryen, slowly rises to power.

The whole series traces the power struggle for the Iron Throne of Westeros, with various factions staking claim to it.

In the fourth book, A Feast For Crows, the War of the Five Kings finally draws to an end. Most of the main disputants for the Iron throne are dead. Jon Snow, the alleged son of Eddard Stark, has now become the Commander of the Night watch. In the absence of King Stannis Baratheon, Joffrey’s eight year old brother, Tommen Baratheon, is now the ruler of King’s Landing, watched over by his mother Cersei Lannister.

The manuscript of A Feast for Crows was so huge that the author was compelled to split it. He decided to split the novel geographically rather than chronologically. For this reason, A Feast For Crows and A Dance With Dragons trace events that take place simultaneously, but in different locations. In A Feast For Crows, the story focuses on the happenings in Westeros, the Riverlands, Dorne, King’s Landing, and the Iron Islands. The events in Essos, Winterfell, and the Wall are covered in A Dance With Dragons.

Cersei Lannister finally realizes her dreams of power as she is now the factual ruler of King’s Landing. She is not as skilled in administration as she is in intrigue and makes many ill-advised moves, making many enemies in the process, leading to her own downfall. The book also follows the events in the Riverlands, the Eyrie, Iron Islands, and Dorne. This book also covers a part of the story of Arya Stark in the East. The rest of her story is covered in the next book.'  WHERE SKU_ID=10000016;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Onetime underground journalist Sandy Blair has traveled far from his radical roots in the ?60s-until the bizarre and brutal murder of a millionaire rock promoter draws him back. As Sandy sets out to investigate the crime, he finds himself on a magical mystery tour of the pent-up passions of his generation. For a new messiah has resurrected the once legendary rock band Nazgul-but with an apocalyptic new beat that is a requiem of demonism, mind control, and death only Sandy may be able to change in time.'  WHERE SKU_ID=10000017;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Fanfeludastic - Indian Review of Books, taut, smart and visually charged.
There is no age bar for reading this collection - Mid day
Kaleidoscopic dance of images and remarkable powers of observation - Deccan Herald

This omnibus edition features the ever-popular adventures of Satyajit Rays enduring creation, the professional sleuth Pradosh C. Mitter (Feluda). In his escapades, Feluda is accompanied by his cousin Topshe and the bumbling crime writer Lalmohan Ganguly (Jatayu). From Jaisalmer to Simla, from the Ellora Caves to Varanasi, the trio traverse fascinating locales to unravel one devious crime after another.

Thrills unlimited - Financial Express
A delightful pastime - Statesman '  WHERE SKU_ID=10000018;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' The protagonist of this book is Swaminathan, a ten year old boy who lives in the fictional town of Malgudi. He lives a simple life and spends his days with his friends Mani and Rajam.

The book details how Swami’s school life changes with the entrance of Rajam. The colonial values instilled in the school also irk Swami. The book also details how Swami flees from home after going through dejecting experiences. All the incidents in Swami’s life change him from the innocent naughty boy to someone who wants to take a revolutionary path. The author details all of Swami’s adventures in British India.

Swami And Friends elaborates on the life of the simpleton who confided only in his grandmother and whose relationships were very emotional and basic in nature. The Guardian acknowledged the novel as one of the world’s best English novels by an Indian author. The stories from Swami And Friends were adapted into a television series called Malgudi Days.'  WHERE SKU_ID=10000019;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' This is a collection of R. K. Narayan’s best stories, in which the fictitious town, Malgudi, springs to life with characters that will remain in your heart forever.

Summary of the Book

In this collection, R. K. Narayan’s best works have been collected under three different sections: From an Astrologer’s Day, From Lawley Road and New Stories.'  WHERE SKU_ID=10000020;
UPDATE BLC_SKU SET LONG_DESCRIPTION='This title brings you the delightfully funny account of a harum scarum schoolboy called Swami, written by one of the greatest writers of our time. Malgudi Schooldays exhilarates all those who step into its world, as Swami’s days are full of action. When he is not creating a mess in the classroom, or making blunders in his exams, he is adventuring down the streets of Malgudi. He is either troubling his grandmother or stoning the school windows after being inspired by a swadeshi demonstration! But the greatest stunt Swami and his friends have to pull off is putting together a cricket team called the Malgudi Cricket Club and challenging the Young Men’s Union to a match. Although they gather a team, things go horribly wrong just before the match. This makes Swami with no other option than running away from home, wanting never to come back again.'  WHERE SKU_ID=10000021;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' Tughlaq by Girish Karnad

This play tells the story of an idealist 14th-century Sultan of Delhi, Muhammad bin Tughluq. It is considered to be an allegory on the Nehru era and contains Karnad’s thoughts on the effects of idealism.

Evam Indrajit by Badal Sircar

This play questions one’s existence and shows how one must strive to find the truth in one’s life. It delves into the thoughts and emotions felt by the educated urban middle class.

Silence! The Court is in Session by Vijay Tendulkar

A group of teaches decide to stage a play in a village. When one of the actors fails to show up, a stagehand is asked to replace him. The others stage a rehearsal to help the man understand the procedures of the court, and one of the cast is charged with infanticide as part of the play. However, the scene turns surreal as the cast makes a startling discovery about the accused member.'  WHERE SKU_ID=10000022;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' Naga-Mandala

A woman attracts the attention of a cobra in her failed attempt to feed a love potion to her wayward husband in this play which delves into the meaning of marriage and faithfulness.

Hayavadana

In this play, a man seeks to understand his inner self through the complicated relationships he shares with the people around him.

Tughlaq

This play tells the story of Muhammad Bin Tughlaq, the idealist 19th century Sultan of Delhi.'  WHERE SKU_ID=10000023;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Prince Hamlet, the son of the deceased king and the nephew of King Claudius, his father''s brother and successor, is the hero of this play. He returns to Denmark to find that his mother has already remarried, marrying his uncle. Soon, the castle grounds are haunted by the King’s ghost and Hamlet decides to meet the spectre. The ghost reveals a secret to Hamlet: his father didn’t die of natural causes. In fact, his uncle poisoned him and usurped the throne. Hamlet begins conspiring with the ghost to exact revenge. However, as events unfold, he begins to find that Claudius isn’t an easy man to catch.'  WHERE SKU_ID=10000024;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Magic, love spells, and an enchanted wood provide the materials for one of Shakespeare’s most delightful comedies. When four young lovers, fleeing the Athenian law and their own mismatched rivalries, take to the forest of Athens, their lives become entangled with a feud between the King and Queen of the Fairies. Some Athenian tradesmen, rehearsing a play for the forthcoming wedding of Duke Theseus and his bride, Hippolyta, unintentionally add to the hilarity. The result is a marvelous mix-up of desire and enchantment, merriment and farce, all touched by Shakespeare’s inimitable vision of the intriguing relationship between art and life, dreams and the waking world.'  WHERE SKU_ID=10000025;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Reference book'  WHERE SKU_ID=10000026;
UPDATE BLC_SKU SET LONG_DESCRIPTION='A Manual on Clinical Surgery is a celebrated book on clinical surgery by Dr. S. Das. The book comprehensively covers the subject, and is the recommended guide for medical students who are preparing for the final MBBS examination. The book features nearly 600 illustrations, including line drawings, radiographs, monochrome and color prints, and even photographs of clinical conditions. It provides detailed information about every part of the body, and a section is dedicated to differential diagnosis at the end of each chapter.'  WHERE SKU_ID=10000027;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' Al-Mefty''s Meningiomas, Second Edition is the definitive guide to meningioma diagnosis, treatment, and surgery, and reflects over a decade of major advances in the diagnosis and management of both intracranial and spinal meningiomas since the first edition was published.

The text begins with important information on anatomy, pathology, and epidemiology, followed by clinical and preoperative considerations. The expert authors then provide detailed descriptions of state-of-the-art surgical approaches listed by anatomical site and special operative considerations for intracranial meningiomas. The book closes with incisive discussion of breakthroughs in radiosurgery, radiotherapy and chemotherapy.'  WHERE SKU_ID=10000028;
UPDATE BLC_SKU SET LONG_DESCRIPTION='The author team of Prescott?s Microbiology continues the tradition of past editions by providing a balanced, comprehensive introduction to all major areas of microbiology. Because of this balance, Microbiology is appropriate for microbiology majors and mixed majors courses. The new authors have focused on readability, artwork, and the integration of several key themes (including evolution, ecology and diversity) throughout the text, making an already superior text even better.'  WHERE SKU_ID=10000029;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Frank Netter’s Atlas of Human Anatomy is a complete reference for students of medical sciences. It helps students understand the complete framework of the Human Body, giving them detailed explanations about the structure, methods used to study them and common ailments. The book teaches readers about understanding the human body from the inside-out, giving them a comprehensive picture. It included vivid illustrations which help readers relate the information in an easier manner. The book will help all undergraduate doctors and students of biology.'  WHERE SKU_ID=10000030;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Benjamin James Sadock, Virginia Alcott Sadock and Pedro Ruiz’s Kaplan and Sadock’s Synopsis of Psychiatry – Eleventh Edition is updated with DSM-5. It offers a complete overview of the entire field of psychiatry for clinicians, residents, students and all others who provide mental health care. The book discusses various concepts in behavioural sciences and clinical psychiatry. Replete with case studies and real-world examples, it serves as a reliable reference guide on the subjects'  WHERE SKU_ID=10000031;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Based on the Second Edition of Marks'' Basic Medical Biochemistry: A Clinical Approach, Marks'' Essentials of Medical Biochemistry has been streamlined to focus on only the most essential biochemical concepts important to medical students. The authors present facts and pathways to emphasize how the underlying biochemistry is related to the body''s overall physiological functions. This text presents patients to the students as the biochemistry is being discussed, which strengthens the link between biochemistry and medicine and allows the student to learn about this interaction as the biochemistry is presented. Each chapter includes clinical and biochemical notes and comments, questions and answers to encourage further thinking, and suggested references for those who would like to pursue a particular topic in more depth'  WHERE SKU_ID=10000032;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Reference book'  WHERE SKU_ID=10000033;
UPDATE BLC_SKU SET LONG_DESCRIPTION='A fundamental and respected resource book in critical care, The ICU Book, Fourth Edition, continues to provide the current and practical guidance that have made it the best-selling text in critical care. The text addresses both the medical and surgical aspects of critical care, delivering the guidance needed to ensure sound, safe and effective treatment for patients in intensive care-regardless of the specialty focus of the unit. Traditionally available as a printed textbook, the print version now comes with a completely revamped digital experience, powered by Inkling.'  WHERE SKU_ID=10000034;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Reference book'  WHERE SKU_ID=10000035;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Christensen''s Physics of Diagnostic Radiology is a comprehensive book for undergraduate students of Medical Sciences. The book comprises chapters on radiation, production of X-rays, filters, stereoscopy, ultrasound, protection, and digital radiography. In addition, the book provides a clear and lucid understanding of the physics principles essential for medical diagnosis. This book is essential for radiologists.'  WHERE SKU_ID=10000036;
UPDATE BLC_SKU SET LONG_DESCRIPTION='The thoroughly revised Seventh Edition of Feigenbaum''s Echocardiography reflects recent changes in the technology and clinical use of echocardiography. Highlights include over 1,600 illustrations, 600 in full color; detailed discussions on the use of three-dimensional echocardiography and perfusion imaging; and new information on the mechanics and utility of Strain and Strain rate imaging. Many new images complement the state-of-the-art information on technological advances. Current AHA/ACC guidelines are included for each chapter.'  WHERE SKU_ID=10000037;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Marketing Management is regarded as one of the best study materials on marketing throughout the world, and Marketing Management: A South Asian Perspective presents various dynamic theories and practices in marketing in such a manner, that the book today is extensively followed by a plethora of people including students, teachers and marketing professionals. This book retains the salient aspects of the previous editions and in addition presents plenty of fresh information on marketing from the global and local perspectives.

One key feature of the updated version of Marketing Management: A South Asian Perspective is that it contains new vignettes at the beginning of each chapter that have the potential to trigger long bouts of meaningful classroom discussions on the subject. In addition, the Marketing Memo and Marketing Insight boxes have been revised in the 14th edition of the book that throws ample light on the challenges and chances marketers might face in rural South East Asia.

Marketing Management: A South Asian Perspective also contains several new subsections and in-text cases that address the drastic alterations that have occurred in the marketing world today. A portion of the subject matter has also been reorganized to put the spotlight on South Asia, which is the focal point of the book. The book emphasizes on holistic marketing and the interdependencies that exist in the global marketing scenario in the present times. The book covers topics like Competitive Dynamics, Tapping into Global Markets, Communicating Value, Setting Product Strategy, and Creating Customer Value and Customer Relationships.

Marketing Management: A South Asian Perspective discusses various marketing issues not only via prosaic information, but also in a more attention-captivating way through lecture slides and files containing test items'  WHERE SKU_ID=10000038;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Services Marketing is a comprehensive book for students of Business Management. The book comprises chapters on consumer behavior in a services context, positioning services in competitive markets, applying the 4Ps of marketing to services, designing and managing the customer interface, and striving for service excellence. In addition, the book includes several case studies and examples to help understand the concepts better. This book is essential for professionals of sales and marketing.'  WHERE SKU_ID=10000039;
UPDATE BLC_SKU SET LONG_DESCRIPTION='K. Aswathappa’s Human Resource Management : Text and Cases 7th Edition is apt for MBA students. The book is divided into multiple sections  so as to give you a better understanding of the subject. The books covers MBA syllabus for students who are specialising in human resources.'  WHERE SKU_ID=10000040;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Complete Business Statistics is a comprehensive book for undergraduate students of Commerce and Finance. The book comprises chapters on probability, random variables, confidence intervals, analysis of variance, simple linear regression, correlation and non-parametric methods, and Chi-square tests. In addition, the book consists of several examples, exercises and statistical applications in finance, economics, government, technology, operations and marketing. This book is essential for students preparing for their postgraduate entrance examinations.'  WHERE SKU_ID=10000041;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' First published in 1934, Security Analysis is one of the most influential financial books ever written. Selling more than one million copies through five editions, it has provided generations of investors with the timeless value investing philosophy and techniques of Benjamin Graham and David L. Dodd.

As relevant today as when they first appeared nearly 75 years ago, the teachings of Benjamin Graham, the father of value investing, have withstood the test of time across a wide diversity of market conditions, countries, and asset classes.

This new sixth edition, based on the classic 1940 version, is enhanced with 200 additional pages of commentary from some of today''s leading Wall Street money managers. These masters of value investing explain why the principles and techniques of Graham and Dodd are still highly relevant even in today''s vastly different markets'  WHERE SKU_ID=10000042;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Ever since Roger Fenton inaugurated the genre by photographing the Crimean War in 1855, the world''s great photojournalists have used a variety of approaches to bear witness to their times. At one end of the photojournalistic spectrum are war photographers like Robert Capa and Larry Burrows, who capture the most extreme events of human existence as they happen; at the other are social documentarians like Lewis Hine and Sebasti+uo Salgado, who step back from the single dramatic incident to cover in depth such economic and cultural issues as labor and migration. By compiling 250 of the most memorable images from photojournalismGCOs 150-year history, Photojournalism 1855 to the Present: EditorGCOs Choice provides a fascinating introduction to the entire range of the field.Author Reuel Golden, a noted authority on photojournalism, selected the fifty-four photographers featured in this book based on their critical reputations and historical importance. For each photographer, Golden provides a portfolio of representative imagesGComany reproduced at full-page sizeGCoas well as a brief biography and an insightful critical commentary on his or her career. In these commentaries and in his informative introduction, Golden discusses the particular challenges of photojournalism, such as the relationship between photographer and subject, and the moral ramifications of aestheticizing human suffering. Yet perhaps most importantly, his text also encourages the reader to look closer and discover how well the photographs speak for themselves. From Frank HurleyGCOs groundbreaking World War I battlefield shots to Mary Ellen MarkGCOs stark portraits of American poverty and James NachtweyGCOs haunting pictures of the September 11 attacks, the images in this book prove that even in our era of twenty-four-hour video-on demand, the still photograph remains as powerful as ever.'  WHERE SKU_ID=10000043;
UPDATE BLC_SKU SET LONG_DESCRIPTION='This Handbook charts the growing area of journalism studies, exploring the current state of theory and setting an agenda for future research in an international context. The volume is structured around theoretical and empirical approaches, and covers scholarship on news production and organizations; news content; journalism and society; and journalism in a global context. Emphasizing comparative and global perspectives, each chapter explores: '  WHERE SKU_ID=10000044;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Data Structures And Algorithms Made Easy In Java is a guide which helps you understand data structures better. Data structures are ways in which data is stored and organised on a computer so as to make it more resourceful. There are different kinds of data structures available for different tasks, with some being highly specific and others used for certain applications. They help in effectively managing large quantities of data with the help of algorithms which, in the fields of mathematics and computer science, is a systematic procedure towards solving any numerical problem. The book covers many topics concerning competitive examinations and includes numerous puzzles and probable interview questions to help the reader prepare better. Each question also comes with multiple solutions of varying complexities so as to enable the reader to deal with a variety of questions. Furthermore, all codes in the book have been written using the Java script. It is a complete preparation guide for likely job aspirants for companies like Oracle, Microsoft, Amazon, Facebook and for people appearing for competitive examinations'  WHERE SKU_ID=10000045;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Introduction to Avionic Systems, Third Edition explains the basic principles and underlying theory of the core avionic systems in modern civil and military aircraft, comprising the pilot''s head-up and head-down displays, data entry and control systems, fly by wire flight control systems, inertial sensor and air data systems, navigation systems, autopilots and flight management systems. The implementation and integration of these systems with current (2010) technology is explained together with the methods adopted to meet the very high safety and integrity requirements. The systems are analysed from the physical laws governing their behaviour, so that the system design and response can be understood and the performance examined. Worked examples are given to show how the theory can be applied and an engineering feel gained from a simplified model. Physical explanations are also set out and the text is structured so that readers can fast forward through the maths, if they so wish. Introduction to Avionic Systems, Third Edition meets the needs of graduates, or equivalent, entering the aerospace industries who have been educated in a wide range of disciplines, for example, electronic engineering, computing science, mathematics, physics, mechanical and aeronautical engineering. It also meets the needs of engineers at all levels working in particular areas of avionics who require an understanding of other avionic systems. Technology is continually advancing and this new third edition has been revised and updated and the presentation improved, where appropriate, The systems coverage has also been increased and a new section on helicopter flight control added.'  WHERE SKU_ID=10000046;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Numerical Heat Transfer And Fluid Flow primarily uses elementary calculus and simple algebra in exploring and developing numerical procedures to predict the behavior of various processes. This is mainly based on physical considerations. The approach is tailored to help augment a deeper understanding of all the crucial aspects of heat transfer and fluid flow. The exercises explored through the text are specifically aimed at improving the ability to analyze and interpret the data and the final computed results.'  WHERE SKU_ID=10000047;
UPDATE BLC_SKU SET LONG_DESCRIPTION='This is the third edition of the book Microwave Devices And Circuits, which is a reference book on the latest in microwave electronic technology. The book is designed to help students who are pursuing courses on microwaves, microwave engineering, physical electronics, and microwave electronics. It also provides extensive information on microwave solid-state devices, microwave tubes, and microwave circuits. The book includes chapters like Introduction Between Electrons and Fields, Electromagnetic Plane Waves, Microwave Transmission Lines, Microwave Waveguides and Components, Microwave Transistors and Tunnel Diodes, Microwave Field-effect Transistors, Transferred Electron Devices (TEDs), Avalanche Transit-time Devices, Microwave Linear-beam Tubes (O type), Microwave Crossed-field Tubes (M type), Striplines, and Monolithic Microwave Integrated Circuits.'  WHERE SKU_ID=10000048;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' Improve Compensation Strategies for Package Shortcomings
In today''s deregulated environment, the nation''s electric power network is forced to operate in a manner for which it was not designed. As a result, precision system analysis is essential to predict and continually update network operating status, estimate current power flows and bus voltages, determine stability limits, and minimize costs.
Computational Methods for Electric Power Systems is an introductory overview of computational methods used for analytical studies in power systems and other engineering and scientific fields. As power systems increasingly operate under stressed conditions, techniques such as computer simulation remain integral to control and security assessment. This volume analyzes the algorithms used in commercial analysis packages and presents salient examples of their implementation that are simple and thorough enough to be reproduced easily. Most of the examples were produced using MATLAB® language.
Presents General Theory Applicable to Different Systems
Commercial packages routinely fail or give erroneous results when used to simulate stressed systems, and understanding their underlying numerical algorithms is imperative to correctly interpret their results. This edition paints a broad picture of the methods used in such packages but omits extraneous detail. It includes new chapters that address function approximation and finite element analysis, in addition to new sections'  WHERE SKU_ID=10000049;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Design of Steel Structures 2nd Edition, authored by L. S. Negi, is a comprehensive textbook for Civil Engineering students. It gives students a detailed account of the aspects and design of simple steel structures.'  WHERE SKU_ID=10000050;
UPDATE BLC_SKU SET LONG_DESCRIPTION='The contemporary study of all computer algorithms can be understood clearly by perusing the contents of Introduction To Algorithms. Although this covers most of the important aspects of algorithms, the concepts have been detailed in a lucid manner, so as to be palatable to readers at all levels of skill.'  WHERE SKU_ID=10000051;
UPDATE BLC_SKU SET LONG_DESCRIPTION='UNIX Concepts And Applications is superb guide for beginners stepping into the world of UNIX. The book is filled with real-world examples that help the reader in understanding the concepts in a better way while the exercises put to test the reader’s understanding of the topics.'  WHERE SKU_ID=10000052;
UPDATE BLC_SKU SET LONG_DESCRIPTION='With a majority rule over the complete software industry, it is very evident that an in-depth knowledge of JAVA is a very crucial factor for software and IT professionals. Core JAVA: An Integrated Approach considers new learners while explaining the concepts of Java in a simple and straightforward manner.'  WHERE SKU_ID=10000053;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Concrete Mathematics: A Foundation for Computer Science is a comprehensive on mathematics which explains the working of an advanced computer programming and algorithms. The book comprises of more than 500 exercises divided into categories like sums, recurrences, integer functions, elementary number theory, binomial coefficients, discrete probability and asymptotic methods. In addition, the book has new material about mechanical summation and an expanded bibliography and index. This book is essential for students pursuing advanced mathematics'  WHERE SKU_ID=10000054;
UPDATE BLC_SKU SET LONG_DESCRIPTION='ndia After Gandhi: The History Of The World''s Largest Democracy, published in 2007, takes an in-depth look into the history of this country, since its independence from the British Raj in 1947. The author has skillfully reconstructed the last six decades of India’s past. Guha explains how the country was divided by religion, caste, language, and yet it established itself as an independent, united, and democratic nation.'  WHERE SKU_ID=10000055;
UPDATE BLC_SKU SET LONG_DESCRIPTION=' Designed for ardent history enthusiasts, India''s Struggle For Independence is one of the most exhaustive and precise account of the struggle of Indian Independence ever written in the literary world. Written and edited by five expert authors, it presents a detailed outlook on one of the most important periods in Indian history.

The facts and details provided in this book have been gathered from oral and written sources, and various other primary sources have been used along with years of intense research. Written with a very concise approach, it is a one of a kind book that details the intricacies of the Indian Independence struggle.

The struggle for Indian Independence took a long time and was something that affected the whole country. Every state in the country boasted of some kind of revolt – minor or major during this period. Numerous revolutionaries throughout the country came together in their efforts to fight against the British rule and set their country free. Few of the chapters in the book are The Fight to Secure Press Freedom, Foundation of the Congress: The Myth, World War I and Indian Nationalism: The Ghadar, An Economic Critique of Colonialism, Peasant Movements and Uprisings after 1857, The Non-Cooperation Movement—1920-1922, The Gathering Storm-1927-1929, Civil Rebellions and Tribal Uprisings, and many more.'  WHERE SKU_ID=10000056;
UPDATE BLC_SKU SET LONG_DESCRIPTION='ndia’s Biggest Cover Up is a sequel to Dhar’s previous book, Back From Dead: Inside The Subhas Bose Mystery, which was released in 2005. Following that, Dhar and his colleagues had begun their research to find out the reason behind Subhash Chandra Bose’s death, and requested extra information from the Ministry of Home Affairs, Indian Prime Minister’s Office, and the Ministry of External Affairs. They also sought information from foreign governments through the Freedom of Information Act and the Right to Information Act.'  WHERE SKU_ID=10000057;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Indian civilization is among the oldest in the world, and what is unique in that respect is that the culture of the peoples still remains largely unchanged, with a strong thread of continuity through the ages.
The Wonder That was India takes a look at the country’s history from the time of the Harappan or Indus Valley Civilization. It explores the possible causes for the decline of the Harappan civilization and settlements. The book talks about the possibility of the Harappans having moved towards the south and settled in the peninsular region.
The author also discusses the Aryan invasion theory, supporting it with various research papers and findings of that time. The evolution of Hindu religion is also talked about in this book—from the Harappan times, to the coming of the Aryans and the mutual influence that Hinduism and its off shoots Jainism and Buddhism had on each other.
This book is comprehensive in its coverage of Indian history. It looks at every aspect of Indian society and culture. The Wonder That was India covers everything from religion, governance, social evolution, literary traditions, philosophy languages, and science.
The author explores the significant role the Hindu religion played on the lives of the people. All the literary compositions of ancient times had religious associations. He also puts forward the theory that the European gypsies are of Indian origin.
The Wonder That Was India also gives an insight into modern Indian society and culture, how it became a confluence of different influences from many a quarter throughout the many stages of its history.'  WHERE SKU_ID=10000058;

UPDATE BLC_SKU SET LONG_DESCRIPTION=' There comes a day in one''s life when one feels it should all be put down before memory fades. There are endless memories and I have carried a story with me for a long time.
SRINAGAR IN THE WINTER OF 1989 was an eerie ghost town witnessing the beginnings of a war dance. The dam burst the night boys from the separatist JKLF group were freed in exchange for the release of Rubaiya Sayeed, the Union home minister''s daughter. As Farooq Abdullah had predicted, the government''s caving in emboldened many Kashmiris into thinking that azaadi was possible. ''The price we will have to pay'' were Farooq''s prophetic words. Killings were almost a daily occurrence. Bomb explosions and firings occurred not far from the chief minister''s residence in the most secure zone. Gun-toting youth in trucks were seen close to the cantonment. Kashmiris believed that they were on the verge of liberation. A.S. Dulat, who was posted there, saw Intelligence Bureau colleagues being picked off one by one.'  WHERE SKU_ID=10000059;

UPDATE BLC_SKU SET LONG_DESCRIPTION='The Last Mughal highlights Dalrymple’s longstanding fascination with the Indian city of Delhi. It presents the Delhi that formed the seat of the Mughal empire in India - a city as brilliant as the monarch who reigned over it. Indeed Bahadur Shah Zafar II embodied the very essence of Delhi city. He was a talented and versatile individual, well-versed in poetry, calligraphy, and mysticism. Despite being under the control of the East India Company to quite an extent, he nevertheless managed to form a dazzling court, setting the stage for one of India’s most culturally rich phases.'  WHERE SKU_ID=10000060;
UPDATE BLC_SKU SET LONG_DESCRIPTION=''  WHERE SKU_ID=10000061;
UPDATE BLC_SKU SET LONG_DESCRIPTION=''  WHERE SKU_ID=10000062;
UPDATE BLC_SKU SET LONG_DESCRIPTION='The hottest new look in fashion jewelry is all about gemstones and pearls. Now readers can create--right at home--their own unique versions of the stylish looks they see on models and in magazines. Using simple, accessible techniques and easily '  WHERE SKU_ID=10000063;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Examining what it is that makes fashion illustration the choice of the moment of art directors and style magazines, this book follows the renaissance predicted by the authors 2000 book, Fashion Illustration Now. Borrellis introduction describes the contemporary mood among these artists and in particular shows how the maturing of the digital age has had a surprising and astonishingly creative effect on the handmade art of illustration. Organized alphabetically by artist and in a similar format to Fashion Illustration Now, the book includes over forty exceptional artists, who capture the mood of contemporary style, show examples of their work and describe their inspiration.'  WHERE SKU_ID=10000064;
UPDATE BLC_SKU SET LONG_DESCRIPTION='Aimed at complete beginners and experienced crafts people looking for new ideas, this unique approach to decorating everyday glass objects to create stylish individual pieces is both a practical guide and a source of inspiration. Creative Glass features a wide range of exciting projects, from those using simple techniques of coiling wire, to more advanced projects involving intricate beadwork or soldering. A comprehensive section of practical information on tools and materials explains the basic techniques of working with wire, beads, and mosaic. All of the projects are accompanied by clear step-by-step photographs, detailed instructions, and stylish inspirational photographs of the finished piece. From pretty holiday baubles to a sophisticated wire woven decanter, there is something to suit every taste and skill level.'  WHERE SKU_ID=10000065;
