-- Menus
INSERT INTO BLC_CMS_MENU (MENU_ID, NAME) VALUES (1, 'Header Nav');

-- Menu Items


INSERT INTO BLC_CMS_MENU_ITEM (MENU_ITEM_ID, PARENT_MENU_ID, SEQUENCE, MENU_ITEM_TYPE, ACTION_URL, LABEL) VALUES (5, 1, 5, 'CATEGORY', '/books', 'Books');

INSERT INTO BLC_CMS_MENU_ITEM (MENU_ITEM_ID, PARENT_MENU_ID, SEQUENCE, MENU_ITEM_TYPE, LINKED_PAGE_ID, LABEL) VALUES (7, 1, 6, 'PAGE', 2, 'FAQ');
